#!/bin/bash

# Variables
USERNAME=$(whoami)
DATE=$(date)
HOSTNAME=$(hostname)
. /etc/os-release
OS="$NAME $VERSION"
UPTIME=$(uptime -p)

CPU=$(lshw -class processor | grep -E "product" | awk -F: '{print $2}')
CPUSPEED=$(lshw -class processor | grep -E "size" | awk -F: '{print $2}')
RAM=$(free -h | grep Mem | awk '{print $2}')
DISK=$(lsblk -d -o name,size,model)
VIDEO=$(lshw -class display | grep product)

FQDN=$(hostname -f)
IPADDR=$(hostname -I | awk '{print $1}')
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS=$(systemd-resolve --status | grep "DNS Servers" -A1 | tail -n1)

INTERFACE=$(ip -o -4 addr show up primary | awk '{print $2}')
NIC_MODEL=$(lshw -class network | grep product)
NIC_IP=$(ip a show $INTERFACE | grep "inet " | awk '{print $2}')

USERS=$(who | awk '{print $1}' | paste -sd "," -)
DISKSPACE=$(df -h --output=source,pcent | tail -n +2)
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGE=$(uptime | grep -ohe 'load average[s:][: ].*' | awk '{print $3,$4,$5}')
MEMORY=$(free -h)
LISTEN_PORTS=$(ss -tuln)
UFW_RULES=$(sudo ufw status numbered)

# Output
cat <<EOF

System Report generated by $USERNAME, $DATE

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Speed: $CPUSPEED
RAM: $RAM
Disk(s): $DISK
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $IPADDR
Gateway IP: $GATEWAY
DNS Server: $DNS

InterfaceName: $NIC_MODEL
IP Address: $NIC_IP

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISKSPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGE
Memory Allocation: $MEMORY
Listening Network Ports: $LISTEN_PORTS
UFW Rules: $UFW_RULES

EOF
